files:
  - source: '**/*'
    ignore:
      - /i18n
      - /img
      - '**/.*'
      - '**/*.yml'
      - /Makefile
      - /*.*
      - /vendor
      - /tst
      - /doc
      - /.github/
      - /css
      - /cfg
      - /js/test
      - /js/base*
      - /js/bootstrap*
      - /js/*.json*
      - /js/raw*
      - /js/common.js
      - /js/jquery*
      - /js/kjua*
      - /js/prettify*
      - /js/purify*
      - /js/showdown*
      - /js/zlib*
    translation: /i18n/%two_letters_code%.json
